title: CESM2 MARBL Solutions
author: MARBL Team
logo: marbl_pic.jpeg
execute:
  execute_notebooks: "off"
repository:
  url: https://github.com/NCAR/marbl-solutions
launch_buttons:
  jupyterhub_url: "https://jupyterhub.hpc.ucar.edu/dev"

