name: marbl-solutions-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - jupyterlab
  - xarray
  - intake-esm
  - pytest
  - pytest-cov
  - pip
  - pip:
      - pre-commit
      - xcollection
      - git+https://github.com/NCAR/esm-collections
