name: marbl-solutions-dev
channels:
  - conda-forge
  - nodefaults
  - ncar
dependencies:
  - jupyterlab
  - xarray
  - pytest
  - pytest-cov
  - holoviews
  - hvplot
  - pop-tools
  - xhistogram
  - geocat-comp
  - panel
  - papermill
  - ipykernel
  - prefect
  - nbformat
  - xpersist
  - xcollection
  - datashader
  - pip
  - pip:
      - pre-commit
      - git+https://github.com/intake/intake-esm
      - git+https://github.com/NCAR/esm-collections
